name: CI/CD GitHub Pages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Execute tests
              run: npm test

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Usar Node.js 22.x
              uses: actions/setup-node@v4
              with:
                node-version: '22.x'

            - name: Install dependencies
              run: npm install
            
            - name: Build application
              run: npm run build

            - name: Publish build artifacts
              uses: actions/upload-artifact@v4
              with:
                name: build-output
                path: build

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                name: build-output
                path: build

            - name: GitHub Pages Deploy
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                artifact_dir: build