name: CI/CD with HTML and Sass for GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm i

      - name: Validate HTML
        run: |
          if command -v html-validate >dev/null 2>&1; then
            npx validate ./*.html
          else
            echo "html-validate not found. Skipping HTML validation."
          fi

      - name: Execute style tests
        run: npm run lint-css
      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      
      - name: Install dependencies
        run: npm i

      - name: Compile Sass to CSS
        run: npm run build-sass

      - name: Publish build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          publish_dir: /
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
